site_name: Visual Novel Club Resources
site_url: https://drinosaret.github.io/vn-club-resources
site_description: Resources page for VN Club Resurrection.
site_author: VN Club Resurrection

theme:
  name: material
  prev_next_buttons_location: both
  logo: assets/favicon2.png
  favicon: assets/favicon2.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - header.social
  palette:
    scheme: default
    primary: indigo
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono

copyright: ""

nav:
  - Home: index.md
  - Where to Find VNs: find.md
  - Where to Get VNs: sources.md
  - Tools: tools.md

extra:
  discord_invite: "https://discord.gg/Ze7dYKVTHf"
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Ze7dYKVTHf
      name: VN Club Resurrection Discord

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji
  - pymdownx.superfences
  - toc:
      permalink: true
  - meta

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - en
        - ja
  - open-in-new-tab