site_name: Visual Novel Club Resources
site_url: https://vnclub.org/
site_description: Learn Japanese with Visual Novels – VN Club Resources
site_author: VN Club Resurrection

theme:
  name: material
  prev_next_buttons_location: both
  logo: assets/favicon2.png
  favicon: assets/favicon2.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - header.social
    - navigation.expand
    - navigation.sections
  palette:
    scheme: default
    primary: indigo
  font:
    text: Roboto
    code: Roboto Mono

copyright: ""

nav:
  - Home: index.md
  - Start Here:
      - The Guide: guide.md
  - Resources:
      - Where to Find VNs: find.md
      - Where to Get VNs: sources.md
      - Tools: tools.md
  - Guides:
      - JL Guide: jl-guide.md
      - Textractor Guide: textractor-guide.md
      - Agent Guide: agent-guide.md
      - OwOCR Guide: owocr-guide.md
      - VNTimeTracker Guide: timetracker-guide.md
      - JDownloader Guide: jdownloader-guide.md
  - Other: 
      - Community: join.md

extra:
  discord_invite: "/join/"
  generator: false


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.emoji
  - toc:
      permalink: true
  - meta

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - en
        - ja
  - open-in-new-tab