site_name: Visual Novel Club Resources
site_url: https://vnclub.org/
site_description: Learn Japanese with Visual Novels – VN Club Resources
site_author: VN Club Resurrection

theme:
  name: material
  prev_next_buttons_location: both
  logo: assets/favicon2.png
  favicon: assets/favicon2.png
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - header.social
    - navigation.expand
    - navigation.sections
    - toc.follow
  palette:
    scheme: default
    primary: indigo
  font:
    text: Roboto
    code: Roboto Mono

copyright: ""

nav:
  - Home: index.md
  - Start Here:
      - The Guide: guide.md
  - Resources:
      - Where to Find VNs: find.md
      - Where to Get VNs: sources.md
      - Tools: tools.md
  - Guides:
      - JL Guide: jl-guide.md
      - Textractor Guide: textractor-guide.md
      - Agent Guide: agent-guide.md
      - OwOCR Guide: owocr-guide.md
      - VNTimeTracker Guide: timetracker-guide.md
      - JDownloader Guide: jdownloader-guide.md
  - Other: 
      - Community: join.md

extra:
  discord_invite: "/join/"
  generator: false


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      toc_depth: 3
  - meta
  - def_list
  - abbr

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang:
        - en
        - ja
  - open-in-new-tab
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true