export interface Level1Word {
  kanji: string;
  reading: string;
  english: string;
}

export const level1Words: Level1Word[] = [
  { kanji: '私', reading: 'わたし', english: 'I; me' },
  { kanji: '何', reading: 'なに', english: 'what' },
  { kanji: '俺', reading: 'おれ', english: 'I; me (casual masculine)' },
  { kanji: '言う', reading: 'いう', english: 'to say; to tell' },
  { kanji: '今', reading: 'いま', english: 'now; the present' },
  { kanji: '思う', reading: 'おもう', english: 'to think; to feel' },
  { kanji: '行く', reading: 'いく', english: 'to go' },
  { kanji: '見る', reading: 'みる', english: 'to see; to look; to watch' },
  { kanji: '人', reading: 'ひと', english: 'person; people' },
  { kanji: '来る', reading: 'くる', english: 'to come' },
  { kanji: '自分', reading: 'じぶん', english: 'oneself; myself' },
  { kanji: '気', reading: 'き', english: 'feeling; spirit; mood' },
  { kanji: 'お前', reading: 'おまえ', english: 'you (casual masculine)' },
  { kanji: '話', reading: 'はなし', english: 'talk; story; conversation' },
  { kanji: '知る', reading: 'しる', english: 'to know' },
  { kanji: '聞く', reading: 'きく', english: 'to hear; to listen; to ask' },
  { kanji: '出る', reading: 'でる', english: 'to go out; to leave; to appear' },
  { kanji: '待つ', reading: 'まつ', english: 'to wait' },
  { kanji: '大丈夫', reading: 'だいじょうぶ', english: 'alright; okay; safe' },
  { kanji: '前', reading: 'まえ', english: 'front; before; previous' },
  { kanji: '何か', reading: 'なにか', english: 'something; somehow' },
  { kanji: '中', reading: 'なか', english: 'inside; middle; during' },
  { kanji: '手', reading: 'て', english: 'hand' },
  { kanji: '今日', reading: 'きょう', english: 'today' },
  { kanji: '顔', reading: 'かお', english: 'face' },
  { kanji: '持つ', reading: 'もつ', english: 'to hold; to have; to own' },
  { kanji: '誰', reading: 'だれ', english: 'who' },
  { kanji: '目', reading: 'め', english: 'eye' },
  { kanji: '入る', reading: 'はいる', english: 'to enter; to go in' },
  { kanji: '早い', reading: 'はやい', english: 'early; fast; quick' },
  { kanji: '違う', reading: 'ちがう', english: 'to differ; to be wrong' },
  { kanji: '帰る', reading: 'かえる', english: 'to return home; to go back' },
  { kanji: '悪い', reading: 'わるい', english: 'bad; wrong; sorry' },
  { kanji: '一', reading: 'いち', english: 'one' },
  { kanji: '考える', reading: 'かんがえる', english: 'to think; to consider' },
  { kanji: '好き', reading: 'すき', english: 'like; fond of; favorite' },
  { kanji: '年', reading: 'とし', english: 'year; age' },
  { kanji: '同じ', reading: 'おなじ', english: 'same; identical' },
  { kanji: '出す', reading: 'だす', english: 'to take out; to put out; to send' },
  { kanji: '時間', reading: 'じかん', english: 'time; hour' },
  { kanji: '前に', reading: 'まえに', english: 'before; previously' },
  { kanji: '男', reading: 'おとこ', english: 'man; male' },
  { kanji: '使う', reading: 'つかう', english: 'to use' },
  { kanji: '僕', reading: 'ぼく', english: 'I; me (polite masculine)' },
  { kanji: '本当に', reading: 'ほんとうに', english: 'really; truly' },
  { kanji: '会う', reading: 'あう', english: 'to meet' },
  { kanji: '声', reading: 'こえ', english: 'voice; sound' },
  { kanji: '方', reading: 'ほう', english: 'direction; way; person (polite)' },
  { kanji: '日', reading: 'ひ', english: 'day; sun' },
  { kanji: '上', reading: 'うえ', english: 'up; above; on top of' },
  { kanji: '戻る', reading: 'もどる', english: 'to return; to go back' },
  { kanji: '見える', reading: 'みえる', english: 'to be visible; to be able to see' },
  { kanji: '次', reading: 'つぎ', english: 'next; following' },
  { kanji: '人間', reading: 'にんげん', english: 'human; person' },
  { kanji: '時', reading: 'とき', english: 'time; when; moment' },
  { kanji: '少し', reading: 'すこし', english: 'a little; a bit' },
  { kanji: '子', reading: 'こ', english: 'child; kid' },
  { kanji: '気持ち', reading: 'きもち', english: 'feeling; mood; sensation' },
  { kanji: '君', reading: 'きみ', english: 'you (familiar)' },
  { kanji: '死ぬ', reading: 'しぬ', english: 'to die' },
  { kanji: '仕事', reading: 'しごと', english: 'work; job; task' },
  { kanji: '作る', reading: 'つくる', english: 'to make; to create; to build' },
  { kanji: '様', reading: 'さま', english: 'appearance; way; manner' },
  { kanji: '入れる', reading: 'いれる', english: 'to put in; to insert; to include' },
  { kanji: '呼ぶ', reading: 'よぶ', english: 'to call; to summon; to invite' },
  { kanji: '心配', reading: 'しんぱい', english: 'worry; concern; anxiety' },
  { kanji: '本当', reading: 'ほんとう', english: 'truth; real; genuine' },
  { kanji: '相手', reading: 'あいて', english: 'partner; companion; opponent' },
  { kanji: '話す', reading: 'はなす', english: 'to speak; to talk; to tell' },
  { kanji: '今度', reading: 'こんど', english: 'this time; next time' },
  { kanji: '教える', reading: 'おしえる', english: 'to teach; to tell; to inform' },
  { kanji: '忘れる', reading: 'わすれる', english: 'to forget' },
  { kanji: '終わる', reading: 'おわる', english: 'to end; to finish' },
  { kanji: '食べる', reading: 'たべる', english: 'to eat' },
  { kanji: '絶対', reading: 'ぜったい', english: 'absolute; definitely; never' },
  { kanji: '誰か', reading: 'だれか', english: 'someone; somebody' },
  { kanji: '全部', reading: 'ぜんぶ', english: 'all; everything; entire' },
  { kanji: '頼む', reading: 'たのむ', english: 'to ask; to request; to rely on' },
  { kanji: '取る', reading: 'とる', english: 'to take; to pick up; to grab' },
  { kanji: '生きる', reading: 'いきる', english: 'to live; to be alive' },
  { kanji: '体', reading: 'からだ', english: 'body' },
  { kanji: '最後', reading: 'さいご', english: 'last; final; end' },
  { kanji: '頭', reading: 'あたま', english: 'head' },
  { kanji: '言葉', reading: 'ことば', english: 'word; language; speech' },
  { kanji: '名前', reading: 'なまえ', english: 'name' },
  { kanji: '必要', reading: 'ひつよう', english: 'necessary; needed; essential' },
  { kanji: '女', reading: 'おんな', english: 'woman; female' },
  { kanji: '家', reading: 'いえ', english: 'house; home; family' },
  { kanji: '場所', reading: 'ばしょ', english: 'place; location; spot' },
  { kanji: '無理', reading: 'むり', english: 'impossible; unreasonable; forced' },
  { kanji: 'お願い', reading: 'おねがい', english: 'please; request; favor' },
  { kanji: '力', reading: 'ちから', english: 'power; strength; force' },
  { kanji: '後', reading: 'あと', english: 'after; later; behind' },
  { kanji: '分かる', reading: 'わかる', english: 'to understand; to know; to realize' },
  { kanji: '見せる', reading: 'みせる', english: 'to show; to display' },
  { kanji: '変わる', reading: 'かわる', english: 'to change; to be different' },
  { kanji: '初めて', reading: 'はじめて', english: 'for the first time' },
  { kanji: '確かに', reading: 'たしかに', english: 'certainly; surely; definitely' },
  { kanji: '逃げる', reading: 'にげる', english: 'to run away; to escape; to flee' },
  { kanji: '世界', reading: 'せかい', english: 'world' },
];
