#!/usr/bin/env bash
# Regenerate requirements.lock and requirements-vcs.txt from requirements.txt.
#
# Run this after editing requirements.txt, then commit all three files.
# The Dockerfile installs from the two generated files, not requirements.txt,
# so an un-regenerated lock means your change simply does not ship.
#
# Usage (from vndb-stats-backend/):
#   ./scripts/lock-requirements.sh
#
# Runs inside python:3.11-slim to match the runtime image, so resolved wheels
# and environment markers match what actually gets installed.

set -euo pipefail

cd "$(dirname "$0")/.."

if ! docker version >/dev/null 2>&1; then
  echo "ERROR: Docker is required (the lock must be resolved on Python 3.11)." >&2
  exit 1
fi

echo "Resolving requirements.txt on python:3.11-slim..."

docker run --rm -v "$PWD:/w" -w /w python:3.11-slim sh -c '
  set -e
  apt-get update -qq && apt-get install -y -qq git >/dev/null 2>&1
  pip install --quiet --upgrade pip uv >/dev/null 2>&1
  uv pip compile requirements.txt --generate-hashes -o /tmp/req.lock
  cp /tmp/req.lock /w/requirements.lock
'

# Split the VCS entry out: a git URL cannot carry a --hash, and pip rejects a
# --require-hashes file that contains any unhashed entry.
python3 - <<'PY'
import io

path = 'requirements.lock'
lines = io.open(path, encoding='utf-8').read().split('\n')

# Replace uv's generated header, which cites the temporary output path.
start = 0
while start < len(lines) and lines[start].startswith('#'):
    start += 1
lines = [
    '# Autogenerated from requirements.txt. Do not edit by hand.',
    '# Regenerate with: cd vndb-stats-backend && ./scripts/lock-requirements.sh',
    '#',
    '# Installed with --require-hashes. The git-sourced package lives in',
    '# requirements-vcs.txt because a VCS URL cannot carry a hash.',
] + lines[start:]

kept, vcs, i = [], [], 0
while i < len(lines):
    line = lines[i]
    if ' @ git+' in line:
        vcs.append(line)
        i += 1
        while i < len(lines) and lines[i].startswith('    #'):
            i += 1
        continue
    kept.append(line)
    i += 1

io.open(path, 'w', encoding='utf-8', newline='\n').write('\n'.join(kept))

header = (
    '# Git-sourced dependencies, kept out of requirements.lock because a VCS URL\n'
    '# cannot carry a --hash and --require-hashes rejects any unhashed entry.\n'
    '# Pinned to full commit SHAs. Their dependencies are resolved and hashed in\n'
    '# requirements.lock, so these install with --no-deps.\n'
)
io.open('requirements-vcs.txt', 'w', encoding='utf-8', newline='\n').write(
    header + '\n'.join(vcs) + '\n'
)

unhashed = []
i = 0
while i < len(kept):
    line = kept[i]
    if line and not line.startswith((' ', '#', '\t')):
        block = [line]
        j = i
        while block[-1].rstrip().endswith(chr(92)) and j + 1 < len(kept):
            j += 1
            block.append(kept[j])
        if '--hash=' not in '\n'.join(block):
            unhashed.append(line)
        i = j + 1
        continue
    i += 1

if unhashed:
    raise SystemExit('ERROR: unhashed entries remain in the lock: %s' % unhashed)

print('requirements.lock      : %d hashed entries' % sum(
    1 for l in kept if l and not l.startswith((' ', '#', '\t'))))
print('requirements-vcs.txt   : %d entry(ies)' % len(vcs))
PY

echo "Done. Commit requirements.txt, requirements.lock and requirements-vcs.txt together."
